defaults:
  - scope:
      path: ""
    values:
      layout: home
  - scope:
      path: ""
      type: "pages"
    values:
      layout: home
      permalink: /src/app/routes/home/home.route.html
